### ISSUE TITLE
Activate not firing

### ISSUE THREAD

**Issue by bendparker** [markdalgleish/bespoke.js#52]
Having trouble with the an event not firing...

var deck;
        deck = bespoke.from('#presentation');
        deck.on('activate', function(event) {
         alert('fire');
         });

this never seems to be fire, however presentation loads correctly.

**Comment by bendparker** [comment]
changed to this code:

 var deck;
        deck = bespoke.from('#presentation', [function (deck2) {
            deck2.on('activate', function(event) {
         alert('fire');
         });   
        }]);

It fires on load now, however fails with the following errors:

 Uncaught TypeError: Cannot set property 'hash' of undefined
Uncaught TypeError: Cannot read property 'from' of undefined

**Comment by bendparker** [comment]
Me being a dummy, i was using an old version...read readme from that version and got it figured out.

**Comment by markdalgleish** [comment]
:)
