### ISSUE TITLE
Themes from the demo as bespoke-temes

### ISSUE THREAD

**Issue by shashi** [markdalgleish/bespoke.js#54]
The themes in the demo are fantastic. It would be cool if they were available as npm packages, like e.g. `bespoke-theme-cube`.

Thanks!

**Comment by markdalgleish** [comment]
Those demo themes are for illustrative purposes only, and not really designed for actual content like the current set of themes.

**Comment by markdalgleish** [comment]
Of course, feel free to make new themes based on them and publish them to npm yourself :)

**Comment by shashi** [comment]
I'm planning to put them all together in a single theme and also make them work properly for content. http://markdalgleish.com/projects/bespoke.js/css/themes.css - what license can I use this under? :P
